/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellGraphRouteImport } from './routes/_shell.graph'
import { Route as ShellRecommendationsRouteImport } from './routes/_shell.recommendations'
import { Route as ShellSkillsRouteImport } from './routes/_shell.skills'
import { Route as ShellJobsIndexRouteImport } from './routes/_shell.jobs.index'
import { Route as ShellJobsJobIdRouteImport } from './routes/_shell.jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGraphRoute = ShellGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecommendationsRoute = ShellRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSkillsRoute = ShellSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJobsIndexRoute = ShellJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJobsJobIdRoute = ShellJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/graph': typeof ShellGraphRoute
  '/recommendations': typeof ShellRecommendationsRoute
  '/skills': typeof ShellSkillsRoute
  '/jobs/$jobId': typeof ShellJobsJobIdRoute
  '/jobs/': typeof ShellJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/graph': typeof ShellGraphRoute
  '/recommendations': typeof ShellRecommendationsRoute
  '/skills': typeof ShellSkillsRoute
  '/jobs/$jobId': typeof ShellJobsJobIdRoute
  '/jobs': typeof ShellJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/graph': typeof ShellGraphRoute
  '/_shell/recommendations': typeof ShellRecommendationsRoute
  '/_shell/skills': typeof ShellSkillsRoute
  '/_shell/jobs/$jobId': typeof ShellJobsJobIdRoute
  '/_shell/jobs/': typeof ShellJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/graph'
    | '/recommendations'
    | '/skills'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/graph'
    | '/recommendations'
    | '/skills'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/graph'
    | '/_shell/recommendations'
    | '/_shell/skills'
    | '/_shell/jobs/$jobId'
    | '/_shell/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/graph': {
      id: '/_shell/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof ShellGraphRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recommendations': {
      id: '/_shell/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof ShellRecommendationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/skills': {
      id: '/_shell/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof ShellSkillsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/jobs/': {
      id: '/_shell/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof ShellJobsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/jobs/$jobId': {
      id: '/_shell/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof ShellJobsJobIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellGraphRoute: typeof ShellGraphRoute
  ShellRecommendationsRoute: typeof ShellRecommendationsRoute
  ShellSkillsRoute: typeof ShellSkillsRoute
  ShellJobsJobIdRoute: typeof ShellJobsJobIdRoute
  ShellJobsIndexRoute: typeof ShellJobsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellGraphRoute: ShellGraphRoute,
  ShellRecommendationsRoute: ShellRecommendationsRoute,
  ShellSkillsRoute: ShellSkillsRoute,
  ShellJobsJobIdRoute: ShellJobsJobIdRoute,
  ShellJobsIndexRoute: ShellJobsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
